import { config } from 'dotenv';
config();

import { collection, addDoc, doc, setDoc } from 'firebase/firestore';
import { db } from './firebase.js';

async function seedProducts() {
  const products = [
    {
      id: '1',
      slug: 'kava-arabika-efiopiya-zerno-250g',
      productType: 'coffee',
      name: 'Кава Арабіка Ефіопія, зерно, 250 г',
      categories: ['Зернова кава', 'Арабіка'],
      price: 550,
      photoUrl: '/products/coffee1.jpg',
      photoWebp: '/products/coffee1.webp',
      images: [
        { url: '/products/coffee1_2.jpg', webp: '/products/coffee1_2.webp' },
        { url: '/products/coffee1_3.jpg', webp: '/products/coffee1_3.webp' },
        { url: '/products/coffee1_4.jpg', webp: '/products/coffee1_4.webp' },
        { url: '/products/coffee1_5.jpg', webp: '/products/coffee1_5.webp' },
        { url: '/products/coffee1_6.jpg', webp: '/products/coffee1_6.webp' },
      ],
      description: 'Ефіопська Арабіка з фруктовими нотами та м’якою кислотністю.',
      detailedDescription:
        '<p>Ця кава виготовлена з відбірних зерен ефіопської Арабіки, вирощеної на високогір’ях Ефіопії, що славляться ідеальними умовами для культивації кави. Смаковий профіль вражає яскравими фруктовими нотами, такими як цитрус і ягоди, з м’якою кислотністю та легким квітковим післясмаком.</p><ul><li>Походження: Ефіопія</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Фруктовий, з нотами цитрусу та ягід</li><li>Обсмаження: Середнє</li><li>Рекомендації: Ідеально для фільтр-кави та еспресо</li></ul>',
      characteristics: {
        origin: 'Ефіопія',
        beanType: '100% Арабіка',
        roastLevel: 'Середнє',
        flavorNotes: 'Цитрус, ягоди, квітковий післясмак',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:30:00Z',
      lastUpdated: '2025-08-22T10:00:00Z',
      sku: 'EA-250G-001',
      stock: 24,
      reviews: [
        {
          user: 'Марія',
          rating: 5,
          text: 'Найсмачніша кава, яку я пробувала останнім часом! Аромат просто неймовірний.',
        },
        {
          user: 'Олександр',
          rating: 4,
          text: 'Смак хороший, але трохи кислувата для мого смаку.',
        },
      ],
    },
    {
      id: '2',
      slug: 'kava-kolumbiya-supremo-melena-250g',
      productType: 'coffee',
      name: 'Кава Колумбія Супремо, мелена, 250 г',
      categories: ['Мелена кава', 'Арабіка'],
      price: 520,
      photoUrl: '/products/coffee2.jpg',
      photoWebp: '/products/coffee2.webp',
      description: 'Колумбійська кава з шоколадно-горіховими відтінками.',
      detailedDescription:
        '<p>Кава Колумбія Супремо — це класичний вибір для тих, хто цінує насичений смак із легкими шоколадними та горіховими відтінками. Вирощена в регіонах Колумбії, ця кава має збалансований смаковий профіль із середньою кислотністю та приємною солодкістю.</p><ul><li>Походження: Колумбія</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Шоколад, горіхи, легка солодкість</li><li>Обсмаження: Середнє</li><li>Рекомендації: Підходить для всіх методів заварювання</li></ul>',
      characteristics: {
        origin: 'Колумбія',
        beanType: '100% Арабіка',
        roastLevel: 'Середнє',
        flavorNotes: 'Шоколад, горіхи, солодкість',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: true,
      newPrice: 480,
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '3',
      slug: 'kava-braziliya-santos-zerno-500g',
      productType: 'coffee',
      name: 'Кава Бразилія Сантос, зерно, 500 г',
      categories: ['Зернова кава', 'Арабіка'],
      price: 890,
      photoUrl: '/products/coffee3.jpg',
      photoWebp: '/products/coffee3.webp',
      description: 'Бразильська Арабіка з шоколадним післясмаком.',
      detailedDescription:
        '<p>Бразильська кава Сантос — це преміальні зерна Арабіки, вирощені на родючих ґрунтах Бразилії. Вона має м’який смак із легкою гірчинкою та вираженим шоколадним післясмаком, що робить її ідеальною для тих, хто любить насичену каву.</p><ul><li>Походження: Бразилія</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Шоколад, легка гірчинка</li><li>Обсмаження: Темне</li><li>Рекомендації: Чудово для еспресо та френч-пресу</li></ul>',
      characteristics: {
        origin: 'Бразилія',
        beanType: '100% Арабіка',
        roastLevel: 'Темне',
        flavorNotes: 'Шоколад, легка гірчинка',
        weight: '500 г',
        processing: 'Суха',
      },
      onSale: true,
      newPrice: 830,
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '4',
      slug: 'kava-latte-miks-rozchynna-200g',
      productType: 'coffee',
      name: 'Кава Латте мікс, розчинна, 200 г',
      categories: ['Розчинна кава', 'Суміші'],
      price: 430,
      photoUrl: '/products/coffee4.jpg',
      photoWebp: '/products/coffee4.webp',
      description: 'Розчинний мікс із кремовою текстурою латте.',
      detailedDescription:
        '<p>Цей розчинний мікс для латте поєднує ніжний смак кави з кремовою молочною текстурою. Легкий у приготуванні, він ідеально підходить для швидкого приготування напою вдома чи в офісі.</p><ul><li>Тип: Розчинна кава</li><li>Смак: Молочний, ніжний</li><li>Вага: 200 г</li><li>Рекомендації: Просто додайте гарячу воду</li></ul>',
      characteristics: {
        type: 'Розчинна кава',
        flavorNotes: 'Молочний, ніжний',
        weight: '200 г',
        preparation: 'Додати гарячу воду',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '5',
      slug: 'kava-espresso-italiyska-zerno-1kg',
      productType: 'coffee',
      name: 'Кава Еспресо Італійська, зерно, 1 кг',
      categories: ['Зернова кава', 'Еспресо'],
      price: 1600,
      photoUrl: '/products/coffee5.jpg',
      photoWebp: '/products/coffee5.webp',
      description: 'Італійський еспресо з оксамитовим післясмаком.',
      detailedDescription:
        '<p>Класична італійська суміш для еспресо, створена для справжніх поціновувачів міцної кави. Ця кава має насичене тіло, багатий аромат і оксамитовий післясмак, що ідеально підходить для ранкового пробудження.</p><ul><li>Походження: Італія</li><li>Тип зерен: Суміш Арабіки</li><li>Смак: Насичений, оксамитовий</li><li>Обсмаження: Темне</li><li>Рекомендації: Ідеально для еспресо-машин</li></ul>',
      characteristics: {
        origin: 'Італія',
        beanType: 'Суміш Арабіки',
        roastLevel: 'Темне',
        flavorNotes: 'Насичений, оксамитовий',
        weight: '1 кг',
        processing: 'Мита',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '6',
      slug: 'kava-mokka-aroma-melena-250g',
      productType: 'coffee',
      name: 'Кава Мокка Арома, мелена, 250 г',
      categories: ['Мелена кава', 'З ароматом'],
      price: 480,
      photoUrl: '/products/coffee6.jpg',
      photoWebp: '/products/coffee6.webp',
      description: 'Мелена кава з ароматом шоколаду та спецій.',
      detailedDescription:
        '<p>Ця мелена кава поєднує насичений смак із виразними нотами шоколаду та спецій, створюючи унікальний ароматичний досвід. Вона ідеально підходить для тих, хто шукає щось особливе.</p><ul><li>Тип зерен: Арабіка</li><li>Смак: Шоколад, спеції, легка солодкість</li><li>Обсмаження: Середнє</li><li>Рекомендації: Для френч-пресу та гейзерної кавоварки</li></ul>',
      characteristics: {
        beanType: '100% Арабіка',
        roastLevel: 'Середнє',
        flavorNotes: 'Шоколад, спеції, солодкість',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: true,
      newPrice: 430,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '7',
      slug: 'kava-keniya-aa-zerno-250g',
      productType: 'coffee',
      name: 'Кава Кенія АА, зерно, 250 г',
      categories: ['Зернова кава', 'Арабіка'],
      price: 620,
      photoUrl: '/products/coffee7.jpg',
      photoWebp: '/products/coffee7.webp',
      description: 'Кенійська кава з фруктовими відтінками.',
      detailedDescription:
        '<p>Преміальна кава з Кенії, що славиться своєю яскравою кислотністю та багатим фруктовим профілем. Нотки ягід і цитрусу роблять кожен ковток незабутнім.</p><ul><li>Походження: Кенія</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Фруктовий, ягідний</li><li>Обсмаження: Середнє</li><li>Рекомендації: Для фільтр-кави та аеропресу</li></ul>',
      characteristics: {
        origin: 'Кенія',
        beanType: '100% Арабіка',
        roastLevel: 'Середнє',
        flavorNotes: 'Ягоди, цитрус',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '8',
      slug: 'chay-chornyy-assam-listovyy-100g',
      productType: 'tea',
      name: 'Чай чорний Ассам, листовий, 100 г',
      categories: ['Чорний чай', 'Листовий'],
      price: 300,
      photoUrl: '/products/tea1.jpg',
      photoWebp: '/products/tea1.webp',
      description: 'Міцний чорний чай з терпкими нотами.',
      detailedDescription:
        '<p>Чорний чай Ассам із Індії відомий своїм міцним смаком і насиченим ароматом. Його терпкі ноти ідеально підходять для ранкового чаювання або зігріваючого напою в холодну пору.</p><ul><li>Походження: Індія, Ассам</li><li>Тип: Чорний чай</li><li>Смак: Терпкий, насичений</li><li>Рекомендації: Заварювати 3-5 хвилин при 90°C</li></ul>',
      characteristics: {
        origin: 'Індія, Ассам',
        teaType: 'Чорний чай',
        flavorNotes: 'Терпкий, насичений',
        weight: '100 г',
        brewingTime: '3-5 хвилин',
        brewingTemp: '90°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '9',
      slug: 'chay-zelenyy-sencha-listovyy-100g',
      productType: 'tea',
      name: 'Чай зелений Сенча, листовий, 100 г',
      categories: ['Зелений чай', 'Листовий'],
      price: 320,
      photoUrl: '/products/tea2.jpg',
      photoWebp: '/products/tea2.webp',
      description: 'Японська Сенча з трав’янистим смаком.',
      detailedDescription:
        '<p>Японський зелений чай Сенча відомий своїм свіжим трав’янистим смаком і легкою солодкістю. Цей чай ідеально підходить для тих, хто прагне бадьорості та гарного настрою.</p><ul><li>Походження: Японія</li><li>Тип: Зелений чай</li><li>Смак: Трав’янистий, солодкуватий</li><li>Рекомендації: Заварювати 1-2 хвилини при 80°C</li></ul>',
      characteristics: {
        origin: 'Японія',
        teaType: 'Зелений чай',
        flavorNotes: 'Трав’янистий, солодкуватий',
        weight: '100 г',
        brewingTime: '1-2 хвилини',
        brewingTemp: '80°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '10',
      slug: 'chay-matcha-premium-poroshkovyy-30g',
      productType: 'tea',
      name: 'Чай матча преміум, порошковий, 30 г',
      categories: ['Матча', 'Японський чай'],
      price: 950,
      photoUrl: '/products/tea3.jpg',
      photoWebp: '/products/tea3.webp',
      description: 'Преміальний матча з багатим смаком.',
      detailedDescription:
        '<p>Цей порошковий чай матча преміум-класу виготовлений із відбірного листя, що забезпечує насичений смак і яскравий зелений колір. Він багатий на антиоксиданти та ідеально підходить для церемоніального вживання або смузі.</p><ul><li>Походження: Японія</li><li>Тип: Матча</li><li>Смак: Насичений, трав’янистий</li><li>Рекомендації: Збивати віночком при 80°C</li></ul>',
      characteristics: {
        origin: 'Японія',
        teaType: 'Матча',
        flavorNotes: 'Насичений, трав’янистий',
        weight: '30 г',
        brewingTime: '1-2 хвилини',
        brewingTemp: '80°C',
      },
      onSale: true,
      newPrice: 870,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '11',
      slug: 'chay-puer-shu-presovanyy-100g',
      productType: 'tea',
      name: 'Чай пуер Шу, пресований, 100 г',
      categories: ['Пуер', 'Китайський чай'],
      price: 680,
      photoUrl: '/products/tea4.jpg',
      photoWebp: '/products/tea4.webp',
      description: 'Китайський пуер із землистим смаком.',
      detailedDescription:
        '<p>Пресований пуер Шу з провінції Юньнань має глибокий землистий смак із м’якими деревними нотами. Цей чай сприяє розслабленню та покращенню травлення.</p><ul><li>Походження: Китай, Юньнань</li><li>Тип: Пуер</li><li>Смак: Землистий, м’який</li><li>Рекомендації: Заварювати 3-5 хвилин при 95°C</li></ul>',
      characteristics: {
        origin: 'Китай, Юньнань',
        teaType: 'Пуер Шу',
        flavorNotes: 'Землистий, деревний',
        weight: '100 г',
        brewingTime: '3-5 хвилин',
        brewingTemp: '95°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '12',
      slug: 'chay-travyanyy-myata-romashka-50g',
      productType: 'tea',
      name: 'Чай трав’яний м’ята-ромашка, 50 г',
      categories: ['Трав’яний чай', 'Без кофеїну'],
      price: 250,
      photoUrl: '/products/tea5.jpg',
      photoWebp: '/products/tea5.webp',
      description: 'Трав’яний чай із м’ятою та ромашкою.',
      detailedDescription:
        '<p>Цей трав’яний збір поєднує освіжаючу м’яту та заспокійливу ромашку, створюючи ідеальний напій для релаксу. Без кофеїну, він підходить для вживання в будь-який час дня.</p><ul><li>Тип: Трав’яний чай</li><li>Смак: М’ятний, квітковий</li><li>Рекомендації: Заварювати 5-7 хвилин при 90°C</li></ul>',
      characteristics: {
        teaType: 'Трав’яний',
        flavorNotes: 'М’ятний, квітковий',
        weight: '50 г',
        caffeine: 'Без кофеїну',
        brewingTime: '5-7 хвилин',
        brewingTemp: '90°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '13',
      slug: 'chay-ulun-molochnyy-100g',
      productType: 'tea',
      name: 'Чай улун молочний, 100 г',
      categories: ['Улун', 'Китайський чай'],
      price: 560,
      photoUrl: '/products/tea6.jpg',
      photoWebp: '/products/tea6.webp',
      description: 'Улун із молочним ароматом.',
      detailedDescription:
        '<p>Китайський улун із ніжним молочним ароматом і квітковими нотами. Його кремовий смак ідеально підходить для поціновувачів вишуканих чаїв.</p><ul><li>Походження: Китай</li><li>Тип: Улун</li><li>Смак: Молочний, квітковий</li><li>Рекомендації: Заварювати 3-5 хвилин при 85°C</li></ul>',
      characteristics: {
        origin: 'Китай',
        teaType: 'Улун',
        flavorNotes: 'Молочний, квітковий',
        weight: '100 г',
        brewingTime: '3-5 хвилин',
        brewingTemp: '85°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '14',
      slug: 'chay-karkade-pelyustky-hibiskusa-100g',
      productType: 'tea',
      name: 'Чай каркаде, пелюстки гібіскуса, 100 г',
      categories: ['Каркаде', 'Трав’яний чай'],
      price: 270,
      photoUrl: '/products/tea7.jpg',
      photoWebp: '/products/tea7.webp',
      images: [{ url: '/products/tea7_2.jpg', webp: '/products/tea7_2.webp' }],
      description: 'Каркаде з кислинкою гібіскуса.',
      detailedDescription:
        '<p>Чай із пелюсток гібіскуса має яскравий рубіновий колір і освіжаючу кислинку. Він багатий на антиоксиданти та сприяє зміцненню імунітету.</p><ul><li>Тип: Трав’яний чай</li><li>Смак: Кислий, освіжаючий</li><li>Рекомендації: Заварювати 5-7 хвилин при 90°C</li></ul>',
      characteristics: {
        teaType: 'Каркаде',
        flavorNotes: 'Кислий, освіжаючий',
        weight: '100 г',
        caffeine: 'Без кофеїну',
        brewingTime: '5-7 хвилин',
        brewingTemp: '90°C',
      },
      onSale: true,
      newPrice: 230,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '15',
      slug: 'french-press-600ml',
      productType: 'accessories-for-coffee',
      name: 'Френч-прес 600 мл',
      categories: ['Аксесуари для кави', 'Посуд'],
      price: 1100,
      photoUrl: '/products/other1.jpg',
      photoWebp: '/products/other1.webp',
      description: 'Френч-прес для ароматної кави.',
      detailedDescription:
        '<p>Стильний френч-прес об’ємом 600 мл дозволяє легко приготувати свіжозаварену каву з багатим ароматом і насиченим смаком. Виготовлений із міцного скла та нержавіючої сталі.</p><ul><li>Об’єм: 600 мл</li><li>Матеріал: Скло, нержавіюча сталь</li><li>Рекомендації: Ідеально для заварювання кави грубого помелу</li></ul>',
      characteristics: {
        type: 'Френч-прес',
        capacity: '600 мл',
        material: 'Скло, нержавіюча сталь',
        recommendedUse: 'Для кави грубого помелу',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '16',
      slug: 'keramichna-turka-500ml',
      productType: 'accessories-for-coffee',
      name: 'Керамічна турка 500 мл',
      categories: ['Аксесуари для кави', 'Посуд'],
      price: 950,
      photoUrl: '/products/other2.jpg',
      photoWebp: '/products/other2.webp',
      description: 'Керамічна турка для кави по-турецьки.',
      detailedDescription:
        '<p>Ця керамічна турка об’ємом 500 мл забезпечує рівномірний нагрів, що дозволяє зберегти аромат і смак кави. Ідеально підходить для традиційного приготування кави по-турецьки.</p><ul><li>Об’єм: 500 мл</li><li>Матеріал: Кераміка</li><li>Рекомендації: Для дрібного помелу кави</li></ul>',
      characteristics: {
        type: 'Турка',
        capacity: '500 мл',
        material: 'Кераміка',
        recommendedUse: 'Для дрібного помелу кави',
      },
      onSale: false,
      newPrice: '',
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '17',
      slug: 'elektrychnyy-kapuchynator',
      productType: 'accessories-for-coffee',
      name: 'Електричний капучинатор',
      categories: ['Аксесуари для кави'],
      price: 1300,
      photoUrl: '/products/other3.jpg',
      photoWebp: '/products/other3.webp',
      description: 'Капучинатор для пінки капучино.',
      detailedDescription:
        '<p>Електричний капучинатор швидко збиває молоко, створюючи ідеальну пінку для капучино чи латте. Компактний і простий у використанні, він стане незамінним помічником для домашньої кав’ярні.</p><ul><li>Тип: Електричний</li><li>Матеріал: Нержавіюча сталь</li><li>Рекомендації: Для молока будь-якої жирності</li></ul>',
      characteristics: {
        type: 'Капучинатор',
        material: 'Нержавіюча сталь',
        power: 'Електричний',
        recommendedUse: 'Для молока будь-якої жирності',
      },
      onSale: true,
      newPrice: 1190,
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '18',
      slug: 'chaynyk-zavaryuvalnyy-sklyanyy-800ml',
      productType: 'accessories-for-tea',
      name: 'Чайник заварювальний скляний 800 мл',
      categories: ['Аксесуари для чаю', 'Посуд'],
      price: 1250,
      photoUrl: '/products/other4.jpg',
      photoWebp: '/products/other4.webp',
      description: 'Скляний чайник для заварювання чаю.',
      detailedDescription:
        '<p>Прозорий заварювальний чайник об’ємом 800 мл дозволяє спостерігати за процесом заварювання, зберігаючи аромат і смак чаю. Виготовлений із термостійкого скла.</p><ul><li>Об’єм: 800 мл</li><li>Матеріал: Скло</li><li>Рекомендації: Для листового чаю</li></ul>',
      characteristics: {
        type: 'Заварювальний чайник',
        capacity: '800 мл',
        material: 'Термостійке скло',
        recommendedUse: 'Для листового чаю',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '19',
      slug: 'nabir-chashok-2sht-keramika',
      productType: 'accessories-sets',
      name: 'Набір чашок 2 шт, кераміка',
      categories: ['Посуд'],
      price: 750,
      photoUrl: '/products/other5.jpg',
      photoWebp: '/products/other5.webp',
      description: 'Керамічні чашки для чаю та кави.',
      detailedDescription:
        '<p>Набір із двох керамічних чашок ідеально підходить для чаю чи кави. Їх стильний дизайн додає затишку вашим зустрічам або моментам відпочинку.</p><ul><li>Кількість: 2 шт</li><li>Матеріал: Кераміка</li><li>Рекомендації: Для гарячих і холодних напоїв</li></ul>',
      characteristics: {
        type: 'Чашки',
        quantity: '2 шт',
        material: 'Кераміка',
        recommendedUse: 'Для чаю та кави',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '20',
      slug: 'konteyner-dlya-zberigannya-kavy-1l',
      productType: 'accessories-for-coffee',
      name: 'Контейнер для зберігання кави, 1 л',
      categories: ['Аксесуари для кави'],
      price: 620,
      photoUrl: '/products/other6.jpg',
      photoWebp: '/products/other6.webp',
      description: 'Герметичний контейнер для кави.',
      detailedDescription:
        '<p>Цей герметичний контейнер об’ємом 1 л забезпечує ідеальні умови для зберігання кави, зберігаючи її свіжість і аромат. Виготовлений із міцних матеріалів.</p><ul><li>Об’єм: 1 л</li><li>Матеріал: Пластик, силікон</li><li>Рекомендації: Для зернової та меленої кави</li></ul>',
      characteristics: {
        type: 'Контейнер',
        capacity: '1 л',
        material: 'Пластик, силікон',
        recommendedUse: 'Для зернової та меленої кави',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '21',
      slug: 'chayne-sytechko-nevalyayka',
      productType: 'accessories-for-tea',
      name: 'Чайне ситечко-неваляйка',
      categories: ['Аксесуари для чаю'],
      price: 280,
      photoUrl: '/products/other7.jpg',
      photoWebp: '/products/other7.webp',
      description: 'Ситечко для заварювання чаю.',
      detailedDescription:
        '<p>Практичне чайне ситечко у формі неваляйки забезпечує зручність заварювання листового чаю. Його унікальна конструкція запобігає перевертанню.</p><ul><li>Матеріал: Нержавіюча сталь</li><li>Рекомендації: Для листового чаю</li></ul>',
      characteristics: {
        type: 'Ситечко',
        material: 'Нержавіюча сталь',
        recommendedUse: 'Для листового чаю',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '22',
      slug: 'kava-gvatemala-antigua-zerno-250g',
      productType: 'coffee',
      name: 'Кава Гватемала Антігуа, зерно, 250 г',
      categories: ['Зернова кава', 'Арабіка'],
      price: 570,
      photoUrl: '/products/coffee8.jpg',
      photoWebp: '/products/coffee8.webp',
      images: [{ url: '/products/coffee8_2.jpg', webp: '/products/coffee8_2.webp' }],
      description: 'Кава з нотами какао та прянощів.',
      detailedDescription:
        '<p>Кава з регіону Антігуа в Гватемалі має багатий смак із нотами какао та прянощів. Вона ідеально підходить для еспресо чи фільтр-методу завдяки своєму збалансованому профілю.</p><ul><li>Походження: Гватемала</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Какао, прянощі</li><li>Обсмаження: Середнє</li><li>Рекомендації: Для еспресо та фільтр-кави</li></ul>',
      characteristics: {
        origin: 'Гватемала',
        beanType: '100% Арабіка',
        roastLevel: 'Середнє',
        flavorNotes: 'Какао, прянощі',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '23',
      slug: 'kava-peru-organik-melena-250g',
      productType: 'coffee',
      name: 'Кава Перу Органік, мелена, 250 г',
      categories: ['Мелена кава', 'Арабіка', 'Органік'],
      price: 540,
      photoUrl: '/products/coffee9.jpg',
      photoWebp: '/products/coffee9.webp',
      description: 'Органічна кава з квітковими нотами.',
      detailedDescription:
        '<p>Ця органічна кава з Перу має м’яке тіло, легкі квіткові відтінки та приємну солодкість. Вона вирощена без використання хімічних добрив, що робить її екологічно чистою.</p><ul><li>Походження: Перу</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Квітковий, солодкуватий</li><li>Обсмаження: Середнє</li><li>Рекомендації: Для всіх методів заварювання</li></ul>',
      characteristics: {
        origin: 'Перу',
        beanType: '100% Арабіка',
        roastLevel: 'Середнє',
        flavorNotes: 'Квітковий, солодкуватий',
        weight: '250 г',
        certification: 'Органік',
        processing: 'Мита',
      },
      onSale: true,
      newPrice: 490,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '24',
      slug: 'kava-espresso-deliciozo-kapsuly-10sht',
      productType: 'coffee',
      name: 'Кава Еспресо Деліціозо, капсули, 10 шт',
      categories: ['Капсульна кава', 'Еспресо'],
      price: 350,
      photoUrl: '/products/coffee10.jpg',
      photoWebp: '/products/coffee10.webp',
      description: 'Капсульна кава з кремовою пінкою.',
      detailedDescription:
        '<p>Капсульна кава Еспресо Деліціозо забезпечує насичений смак і стійку кремову пінку. Сумісна з більшістю популярних кавомашин, вона ідеально підходить для швидкого приготування еспресо.</p><ul><li>Тип: Капсульна кава</li><li>Смак: Насичений, кремовий</li><li>Кількість: 10 капсул</li><li>Рекомендації: Для кавомашин</li></ul>',
      characteristics: {
        type: 'Капсульна кава',
        flavorNotes: 'Насичений, кремовий',
        quantity: '10 капсул',
        compatibility: 'Сумісна з Nespresso',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '25',
      slug: 'kava-indoneziya-sumatra-zerno-500g',
      productType: 'coffee',
      name: 'Кава Індонезія Суматра, зерно, 500 г',
      categories: ['Зернова кава', 'Арабіка'],
      price: 920,
      photoUrl: '/products/coffee11.jpg',
      photoWebp: '/products/coffee11.webp',
      description: 'Кава з землистим смаком і шоколадними нотами.',
      detailedDescription:
        '<p>Зерна з острова Суматра відомі своїм насиченим землистим смаком із відтінками темного шоколаду. Ця кава ідеально підходить для гурманів, які цінують глибокий смаковий профіль.</p><ul><li>Походження: Індонезія</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Землистий, шоколадний</li><li>Обсмаження: Темне</li><li>Рекомендації: Для еспресо та френч-пресу</li></ul>',
      characteristics: {
        origin: 'Індонезія, Суматра',
        beanType: '100% Арабіка',
        roastLevel: 'Темне',
        flavorNotes: 'Землистий, темний шоколад',
        weight: '500 г',
        processing: 'Мокра',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '26',
      slug: 'kava-arabika-robusta-melena-250g',
      productType: 'coffee',
      name: 'Кава Арабіка + Робуста, мелена, 250 г',
      categories: ['Мелена кава', 'Суміші'],
      price: 460,
      photoUrl: '/products/coffee12.jpg',
      photoWebp: '/products/coffee12.webp',
      description: 'Суміш для міцного смаку.',
      detailedDescription:
        '<p>Ця суміш Арабіки та Робусти забезпечує міцний смак і насичений аромат, ідеальний для ранкового пробудження. Поєднання двох типів зерен створює збалансований напій із легкою гірчинкою.</p><ul><li>Тип зерен: Арабіка + Робуста</li><li>Смак: Міцний, насичений</li><li>Обсмаження: Середнє</li><li>Рекомендації: Для еспресо та гейзерної кавоварки</li></ul>',
      characteristics: {
        beanType: 'Арабіка + Робуста',
        roastLevel: 'Середнє',
        flavorNotes: 'Міцний, насичений, легка гірчинка',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: true,
      newPrice: 410,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '27',
      slug: 'kava-efiopiya-yrgacheffe-zerno-250g',
      productType: 'tea',
      name: 'Кава Ефіопія Йргачеффе, зерно, 250 г',
      categories: ['Зернова кава', 'Арабіка'],
      price: 640,
      photoUrl: '/products/coffee13.jpg',
      photoWebp: '/products/coffee13.webp',
      images: [{ url: '/products/coffee13_2.jpg', webp: '/products/coffee13_2.webp' }],
      description: 'Кава з квітковими та цитрусовими нотами.',
      detailedDescription:
        '<p>Кава з регіону Йргачеффе в Ефіопії славиться своїм унікальним смаковим профілем із квітковими та цитрусовими нотами. Це один із найпопулярніших сортів для поціновувачів легкої кави.</p><ul><li>Походження: Ефіопія</li><li>Тип зерен: 100% Арабіка</li><li>Смак: Квітковий, цитрусовий</li><li>Обсмаження: Світле</li><li>Рекомендації: Для фільтр-кави та аеропресу</li></ul>',
      characteristics: {
        origin: 'Ефіопія, Йргачеффе',
        beanType: '100% Арабіка',
        roastLevel: 'Світле',
        flavorNotes: 'Квітковий, цитрусовий',
        weight: '250 г',
        processing: 'Мита',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '28',
      slug: 'chay-chornyy-erl-grey-100g',
      productType: 'tea',
      name: 'Чай чорний Ерл Грей, 100 г',
      categories: ['Чорний чай', 'Ароматизований'],
      price: 310,
      photoUrl: '/products/tea1.jpg',
      photoWebp: '/products/tea1.webp',
      description: 'Чорний чай із бергамотом.',
      detailedDescription:
        '<p>Класичний чорний чай Ерл Грей ароматизований натуральною олією бергамоту, що надає йому яскравий цитрусовий аромат і витончений смак.</p><ul><li>Походження: Індія</li><li>Тип: Чорний чай</li><li>Смак: Цитрусовий, бергамот</li><li>Рекомендації: Заварювати 3-5 хвилин при 90°C</li></ul>',
      characteristics: {
        origin: 'Індія',
        teaType: 'Чорний чай',
        flavorNotes: 'Цитрусовий, бергамот',
        weight: '100 г',
        brewingTime: '3-5 хвилин',
        brewingTemp: '90°C',
      },
      onSale: true,
      newPrice: 270,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '29',
      slug: 'chay-zelenyy-zhasmyn-100g',
      productType: 'tea',
      name: 'Чай зелений Жасмин, 100 г',
      categories: ['Зелений чай', 'Ароматизований'],
      price: 330,
      photoUrl: '/products/tea8.jpg',
      photoWebp: '/products/tea8.webp',
      description: 'Зелений чай із жасминовим ароматом.',
      detailedDescription:
        '<p>Цей зелений чай із пелюстками жасмину поєднує ніжний смак і насичений квітковий аромат. Ідеально підходить для легкого чаювання протягом дня.</p><ul><li>Походження: Китай</li><li>Тип: Зелений чай</li><li>Смак: Квітковий, жасминовий</li><li>Рекомендації: Заварювати 2-3 хвилини при 80°C</li></ul>',
      characteristics: {
        origin: 'Китай',
        teaType: 'Зелений чай',
        flavorNotes: 'Квітковий, жасминовий',
        weight: '100 г',
        brewingTime: '2-3 хвилини',
        brewingTemp: '80°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '30',
      slug: 'chay-ulun-tayvanskiy-100g',
      productType: 'tea',
      name: 'Чай улун Тайваньський, 100 г',
      categories: ['Улун', 'Китайський чай'],
      price: 600,
      photoUrl: '/products/tea9.jpg',
      photoWebp: '/products/tea9.webp',
      description: 'Тайванський улун із медовими нотами.',
      detailedDescription:
        '<p>Тайванський улун відомий своїм багатим букетом із квіткових і медових відтінків. Цей чай витримує кілька заварювань, розкриваючи нові грані смаку.</p><ul><li>Походження: Тайвань</li><li>Тип: Улун</li><li>Смак: Квітковий, медовий</li><li>Рекомендації: Заварювати 3-5 хвилин при 85°C</li></ul>',
      characteristics: {
        origin: 'Тайвань',
        teaType: 'Улун',
        flavorNotes: 'Квітковий, медовий',
        weight: '100 г',
        brewingTime: '3-5 хвилин',
        brewingTemp: '85°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '31',
      slug: 'chay-puer-shen-presovanyy-100g',
      productType: 'tea',
      name: 'Чай пуер Шен, пресований, 100 г',
      categories: ['Пуер', 'Китайський чай'],
      price: 700,
      photoUrl: '/products/tea10.jpg',
      photoWebp: '/products/tea10.webp',
      description: 'Зелений пуер із трав’янистим смаком.',
      detailedDescription:
        '<p>Молодий зелений пуер Шен із провінції Юньнань має свіжий трав’янистий смак і легкий аромат. Цей чай ідеально підходить для щоденного вживання.</p><ul><li>Походження: Китай, Юньнань</li><li>Тип: Пуер</li><li>Смак: Трав’янистий, свіжий</li><li>Рекомендації: Заварювати 3-5 хвилин при 90°C</li></ul>',
      characteristics: {
        origin: 'Китай, Юньнань',
        teaType: 'Пуер Шен',
        flavorNotes: 'Трав’янистий, свіжий',
        weight: '100 г',
        brewingTime: '3-5 хвилин',
        brewingTemp: '90°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '32',
      slug: 'chay-karkade-z-myatoyu-100g',
      productType: 'tea',
      name: 'Чай каркаде з м’ятою, 100 г',
      categories: ['Каркаде', 'Трав’яний чай'],
      price: 290,
      photoUrl: '/products/tea11.jpg',
      photoWebp: '/products/tea11.webp',
      description: 'Каркаде з освіжаючою м’ятою.',
      detailedDescription:
        '<p>Поєднання пелюсток гібіскуса та свіжої м’яти створює освіжаючий напій із легкою кислинкою. Цей чай ідеально підходить для спекотних днів або вечірнього релаксу.</p><ul><li>Тип: Трав’яний чай</li><li>Смак: Кислий, м’ятний</li><li>Рекомендації: Заварювати 5-7 хвилин при 90°C</li></ul>',
      characteristics: {
        teaType: 'Каркаде',
        flavorNotes: 'Кислий, м’ятний',
        weight: '100 г',
        caffeine: 'Без кофеїну',
        brewingTime: '5-7 хвилин',
        brewingTemp: '90°C',
      },
      onSale: true,
      newPrice: 250,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '33',
      slug: 'chay-travyanyy-imbir-lymon-50g',
      productType: 'tea',
      name: 'Чай трав’яний Імбир-Лимон, 50 г',
      categories: ['Трав’яний чай', 'Без кофеїну'],
      price: 260,
      photoUrl: '/products/tea12.jpg',
      photoWebp: '/products/tea12.webp',
      description: 'Трав’яний чай з імбиром і лимоном.',
      detailedDescription:
        '<p>Цей трав’яний збір із імбиру та лимона заряджає енергією та підтримує імунітет. Без кофеїну, він підходить для вживання в будь-який час дня.</p><ul><li>Тип: Трав’яний чай</li><li>Смак: Пряний, цитрусовий</li><li>Рекомендації: Заварювати 5-7 хвилин при 90°C</li></ul>',
      characteristics: {
        teaType: 'Трав’яний',
        flavorNotes: 'Пряний, цитрусовий',
        weight: '50 г',
        caffeine: 'Без кофеїну',
        brewingTime: '5-7 хвилин',
        brewingTemp: '90°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '34',
      slug: 'chay-bilyy-bay-mu-dan-50g',
      productType: 'tea',
      name: 'Чай білий Бай Му Дань, 50 г',
      categories: ['Білий чай', 'Китайський чай'],
      price: 580,
      photoUrl: '/products/tea13.jpg',
      photoWebp: '/products/tea13.webp',
      images: [{ url: '/products/tea13_2.jpg', webp: '/products/tea13_2.webp' }],
      description: 'Білий чай із квітковим ароматом.',
      detailedDescription:
        '<p>Рідкісний білий чай Бай Му Дань із Китаю відомий своїм ніжним квітковим ароматом і солодкуватим смаком. Цей чай є одним із найвишуканіших у світі.</p><ul><li>Походження: Китай</li><li>Тип: Білий чай</li><li>Смак: Квітковий, солодкуватий</li><li>Рекомендації: Заварювати 2-3 хвилини при 80°C</li></ul>',
      characteristics: {
        origin: 'Китай',
        teaType: 'Білий чай',
        flavorNotes: 'Квітковий, солодкуватий',
        weight: '50 г',
        brewingTime: '2-3 хвилини',
        brewingTemp: '80°C',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '35',
      slug: 'nabir-lozhechok-dlya-kavy-4sht',
      productType: 'accessories-for-coffee',
      name: 'Набір ложечок для кави, 4 шт',
      categories: ['Аксесуари для кави', 'Посуд'],
      price: 420,
      photoUrl: '/products/other8.jpg',
      photoWebp: '/products/other8.webp',
      description: 'Ложечки для кави та десертів.',
      detailedDescription:
        '<p>Комплект із чотирьох маленьких ложечок із нержавіючої сталі ідеально підходить для подачі кави чи десертів. Їх елегантний дизайн додає вишуканості вашому столу.</p><ul><li>Кількість: 4 шт</li><li>Матеріал: Нержавіюча сталь</li><li>Рекомендації: Для кави та десертів</li></ul>',
      characteristics: {
        type: 'Ложечки',
        quantity: '4 шт',
        material: 'Нержавіюча сталь',
        recommendedUse: 'Для кави та десертів',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '36',
      slug: 'metaleva-turka-400ml',
      productType: 'accessories-for-coffee',
      name: 'Металева турка 400 мл',
      categories: ['Аксесуари для кави', 'Посуд'],
      price: 1050,
      photoUrl: '/products/other9.jpg',
      photoWebp: '/products/other9.webp',
      description: 'Турка для класичного приготування кави.',
      detailedDescription:
        '<p>Турка з нержавіючої сталі об’ємом 400 мл ідеально підходить для приготування кави по-турецьки. Вона міцна, довговічна та забезпечує рівномірний нагрів.</p><ul><li>Об’єм: 400 мл</li><li>Матеріал: Нержавіюча сталь</li><li>Рекомендації: Для дрібного помелу кави</li></ul>',
      characteristics: {
        type: 'Турка',
        capacity: '400 мл',
        material: 'Нержавіюча сталь',
        recommendedUse: 'Для дрібного помелу кави',
      },
      onSale: true,
      newPrice: 980,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '37',
      slug: 'nabir-chashok-4sht-sklo',
      productType: 'accessories-sets',
      name: 'Набір чашок 4 шт, скло',
      categories: ['Посуд'],
      price: 480,
      photoUrl: '/products/other10.jpg',
      photoWebp: '/products/other10.webp',
      images: [{ url: '/products/other10_2.jpg', webp: '/products/other10_2.webp' }],
      description: 'Скляні чашки для чаю та кави.',
      detailedDescription:
        '<p>Набір із чотирьох прозорих скляних чашок із мінімалістичним дизайном. Ідеально підходить для подачі гарячих або холодних напоїв.</p><ul><li>Кількість: 4 шт</li><li>Матеріал: Скло</li><li>Рекомендації: Для чаю та кави</li></ul>',
      characteristics: {
        type: 'Чашки',
        quantity: '4 шт',
        material: 'Скло',
        recommendedUse: 'Для чаю та кави',
      },
      onSale: true,
      newPrice: 380,
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '38',
      slug: 'termos-dlya-kavy-500ml',
      productType: 'accessories-for-coffee',
      name: 'Термос для кави 500 мл',
      categories: ['Аксесуари для кави'],
      price: 890,
      photoUrl: '/products/other11.jpg',
      photoWebp: '/products/other11.webp',
      description: 'Термос зі збереженням температури.',
      detailedDescription:
        '<p>Цей термос об’ємом 500 мл зберігає температуру кави до 8 годин. Його стильний дизайн і компактність роблять його ідеальним для подорожей.</p><ul><li>Об’єм: 500 мл</li><li>Матеріал: Нержавіюча сталь</li><li>Рекомендації: Для гарячих і холодних напоїв</li></ul>',
      characteristics: {
        type: 'Термос',
        capacity: '500 мл',
        material: 'Нержавіюча сталь',
        heatRetention: 'До 8 годин',
        recommendedUse: 'Для гарячих і холодних напоїв',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '39',
      slug: 'zavarnik-dlya-chayu-z-sytechkom-600ml',
      productType: 'accessories-for-tea',
      name: 'Заварник для чаю з ситечком, 600 мл',
      categories: ['Аксесуари для чаю', 'Посуд'],
      price: 990,
      photoUrl: '/products/other12.jpg',
      photoWebp: '/products/other12.webp',
      description: 'Скляний заварник із ситечком.',
      detailedDescription:
        '<p>Скляний заварник із вбудованим ситечком об’ємом 600 мл дозволяє легко заварювати листовий чай, зберігаючи його аромат і смак.</p><ul><li>Об’єм: 600 мл</li><li>Матеріал: Скло, нержавіюча сталь</li><li>Рекомендації: Для листового чаю</li></ul>',
      characteristics: {
        type: 'Заварник',
        capacity: '600 мл',
        material: 'Скло, нержавіюча сталь',
        recommendedUse: 'Для листового чаю',
      },
      onSale: false,
      newPrice: '',
      isRecommended: false,
      dateAdded: '2025-08-20T12:20:00Z',
    },
    {
      id: '40',
      slug: 'podarunkovyy-nabir-kava-chashka',
      productType: 'gift-sets',
      name: 'Подарунковий набір: кава + чашка',
      categories: ['Подарункові набори'],
      price: 1450,
      photoUrl: '/products/other13.jpg',
      photoWebp: '/products/other13.webp',
      description: 'Набір кави та стильної чашки.',
      detailedDescription:
        '<p>Цей подарунковий набір включає відбірну каву та стильну керамічну чашку. Ідеальний подарунок для поціновувачів кави та затишних моментів.</p><ul><li>Склад: Кава 250 г, керамічна чашка</li><li>Рекомендації: Для подарунка або особистого використання</li></ul>',
      characteristics: {
        type: 'Подарунковий набір',
        contents: 'Кава 250 г, керамічна чашка',
        recommendedUse: 'Для подарунка або особистого використання',
      },
      onSale: true,
      newPrice: 1350,
      isRecommended: true,
      dateAdded: '2025-08-20T12:20:00Z',
    },
  ];

  /*try {
    for (const product of products) {
      await addDoc(collection(db, 'products'), product);
      console.log(`Добавлен товар: ${product.name}`);
    }
    console.log('Все товары успешно добавлены!');
  } catch (err) {
    console.error('Ошибка при добавлении товаров:', err);
  }*/

  try {
    for (const product of products) {
      const productRef = doc(db, 'products', product.id);
      await setDoc(productRef, product, { merge: true });
      console.log(`Обновлён/создан товар: ${product.name}`);
    }
    console.log('Все товары успешно добавлены или обновлены!');
  } catch (err) {
    console.error('Ошибка при обновлении товаров:', err);
  }
}

seedProducts();
